---
- hosts: localhost
  gather_facts: false
  collections: 
    - community.kubernetes
    - community.general
  tasks:
    - name: Delete the namespace 
      k8s:
        template: project.j2
        state: absent
        wait: true
    - name: Delete the machineconfig editor role
      k8s:
        template: clusterrole.j2
        state: absent
    - name: Delete the rolebinding 
      k8s:
        template: clusterrolebinding.j2
        state: absent
